import type { FormDefinition } from './types'
export const forms:FormDefinition[]=[
{id:'expense-reimbursement',title:'Expense reimbursement',description:'Prepare a business expense claim, validate policy-required fields, then route it to a human for final approval.',category:'Work admin',risk:'medium',estimatedMinutes:8,fields:[
{key:'merchant',label:'Merchant',type:'text',required:true,placeholder:'e.g. Acme Hotel'},{key:'amount',label:'Amount (USD)',type:'number',required:true,placeholder:'245.50'},{key:'date',label:'Expense date',type:'date',required:true},{key:'category',label:'Category',type:'select',required:true,options:['Travel','Meals','Software','Office','Other']},{key:'businessPurpose',label:'Business purpose',type:'textarea',required:true,placeholder:'Why was this expense necessary?'},{key:'costCenter',label:'Cost center',type:'text',required:true,placeholder:'e.g. ENG-PLATFORM'},{key:'receiptUrl',label:'Receipt URL',type:'text',help:'Demo URL is sufficient for this hackathon build.'}]},
{id:'community-event-permit',title:'Community event permit',description:'Draft a neighborhood event request while keeping the final public-space submission under explicit human control.',category:'Civic life',risk:'high',estimatedMinutes:12,fields:[
{key:'eventName',label:'Event name',type:'text',required:true},{key:'eventDate',label:'Event date',type:'date',required:true},{key:'location',label:'Location',type:'text',required:true,placeholder:'Park / street / venue'},{key:'attendees',label:'Expected attendees',type:'number',required:true},{key:'contactEmail',label:'Organizer email',type:'email',required:true},{key:'soundAmplification',label:'Amplified sound?',type:'select',required:true,options:['No','Yes']},{key:'notes',label:'Operational notes',type:'textarea',placeholder:'Accessibility, cleanup, road closure details…'}]},
{id:'vendor-onboarding',title:'Vendor onboarding request',description:'Let an agent assemble a vendor request and surface risk signals before a human commits company spend or data access.',category:'Procurement',risk:'high',estimatedMinutes:10,fields:[
{key:'vendorName',label:'Vendor name',type:'text',required:true},{key:'service',label:'Service provided',type:'textarea',required:true},{key:'annualSpend',label:'Estimated annual spend (USD)',type:'number',required:true},{key:'dataAccess',label:'Will the vendor access company/customer data?',type:'select',required:true,options:['No','Yes']},{key:'ownerEmail',label:'Internal owner',type:'email',required:true},{key:'securityNotes',label:'Security / privacy notes',type:'textarea'}]}
]
