import { forms } from './data'
import type { AuditEvent,Draft,PersistedState } from './types'
const STORAGE_KEY='approvaldesk:webmcp:v1'; const listeners=new Set<()=>void>(); const now=()=>new Date().toISOString(); const makeId=(p:string)=>`${p}_${crypto.randomUUID().slice(0,8)}`
const seed:PersistedState={drafts:[{id:'draft_demo_1',formId:'expense-reimbursement',status:'awaiting_approval',values:{merchant:'Northstar Hotel',amount:286.4,date:new Date().toISOString().slice(0,10),category:'Travel',businessPurpose:'Customer workshop travel — lodging for one night.',costCenter:'CUSTOMER-SUCCESS',receiptUrl:'https://example.com/receipt/NS-1842'},createdAt:now(),updatedAt:now()}],audit:[{id:'evt_seed',ts:now(),actor:'agent',action:'approval_requested',detail:'Prepared travel reimbursement and requested a human decision.',draftId:'draft_demo_1'}]}
function load():PersistedState{try{const raw=localStorage.getItem(STORAGE_KEY);if(raw)return JSON.parse(raw)}catch{}return structuredClone(seed)}
let state=load(); function persist(){state=structuredClone(state);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));listeners.forEach(l=>l())} function audit(actor:AuditEvent['actor'],action:string,detail:string,draftId?:string){state.audit.unshift({id:makeId('evt'),ts:now(),actor,action,detail,draftId});state.audit=state.audit.slice(0,80)}
export const store={
subscribe(l:()=>void){listeners.add(l);return()=>listeners.delete(l)},snapshot(){return state},reset(){state=structuredClone(seed);persist();return state},
listForms(){return forms.map(({fields,...f})=>({...f,fieldCount:fields.length}))},getForm(id:string){return forms.find(f=>f.id===id)},getDraft(id:string){return state.drafts.find(d=>d.id===id)},
createDraft(formId:string,actor:AuditEvent['actor']='agent'){const form=this.getForm(formId);if(!form)throw new Error(`Unknown form: ${formId}`);const d:Draft={id:makeId('draft'),formId,status:'draft',values:{},createdAt:now(),updatedAt:now()};state.drafts.unshift(d);audit(actor,'draft_created',`Created “${form.title}” draft.`,d.id);persist();return d},
updateFields(draftId:string,values:Record<string,string|number>,actor:AuditEvent['actor']='agent'){const d=this.getDraft(draftId);if(!d)throw new Error(`Unknown draft: ${draftId}`);if(d.status==='submitted')throw new Error('Submitted drafts are immutable.');const form=this.getForm(d.formId);if(!form)throw new Error('Draft references an unknown form.');const allowed=new Set(form.fields.map(f=>f.key));const safe=Object.entries(values).filter(([k])=>allowed.has(k));d.values={...d.values,...Object.fromEntries(safe)};if(d.status==='rejected'||d.status==='approved'||d.status==='awaiting_approval'){d.status='draft';d.approvalNote=undefined}d.updatedAt=now();audit(actor,'draft_updated',`Updated ${safe.length} field${safe.length===1?'':'s'}.`,d.id);persist();return d},
validate(draftId:string){const d=this.getDraft(draftId);if(!d)throw new Error(`Unknown draft: ${draftId}`);const form=this.getForm(d.formId);if(!form)throw new Error('Draft references an unknown form.');const missing=form.fields.filter(f=>f.required).filter(f=>{const v=d.values[f.key];return v===undefined||v===null||String(v).trim()===''}).map(f=>({key:f.key,label:f.label}));const warnings:string[]=[];if(d.formId==='vendor-onboarding'&&Number(d.values.annualSpend??0)>=10000)warnings.push('Annual spend is ≥ $10,000 — finance review is recommended.');if(d.formId==='vendor-onboarding'&&d.values.dataAccess==='Yes')warnings.push('Vendor data access is enabled — security/privacy review is recommended.');if(d.formId==='community-event-permit'&&Number(d.values.attendees??0)>=100)warnings.push('Large event: confirm crowd, accessibility, and cleanup plans.');return{valid:missing.length===0,missing,warnings}},
requestApproval(draftId:string,actor:AuditEvent['actor']='agent'){const d=this.getDraft(draftId);if(!d)throw new Error(`Unknown draft: ${draftId}`);if(d.status==='submitted')throw new Error('Submitted drafts are immutable.');const v=this.validate(draftId);if(!v.valid)throw new Error(`Draft is incomplete: ${v.missing.map(x=>x.label).join(', ')}`);d.status='awaiting_approval';d.updatedAt=now();audit(actor,'approval_requested','Validation passed; human approval requested.',d.id);persist();return{draft:d,validation:v}},
decide(draftId:string,decision:'approve'|'reject',note=''){const d=this.getDraft(draftId);if(!d)throw new Error(`Unknown draft: ${draftId}`);if(d.status!=='awaiting_approval')throw new Error('Draft is not awaiting approval.');d.status=decision==='approve'?'approved':'rejected';d.approvalNote=note;d.updatedAt=now();audit('human',decision==='approve'?'approved':'rejected',note||`Human ${decision}d the draft.`,d.id);persist();return d},
submit(draftId:string,actor:AuditEvent['actor']='agent'){const d=this.getDraft(draftId);if(!d)throw new Error(`Unknown draft: ${draftId}`);if(d.status!=='approved')throw new Error('HUMAN_APPROVAL_REQUIRED: this action cannot run until a human explicitly approves the draft.');d.status='submitted';d.submittedAt=now();d.updatedAt=now();audit(actor,'submitted','Submitted after explicit human approval.',d.id);persist();return d},audit(draftId?:string){return draftId?state.audit.filter(e=>e.draftId===draftId):state.audit}}
